// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.2
// source: proto/account.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountClientClient is the client API for AccountClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountClientClient interface {
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error)
}

type accountClientClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountClientClient(cc grpc.ClientConnInterface) AccountClientClient {
	return &accountClientClient{cc}
}

func (c *accountClientClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/proto.AccountClient/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountClientServer is the server API for AccountClient service.
// All implementations must embed UnimplementedAccountClientServer
// for forward compatibility
type AccountClientServer interface {
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	mustEmbedUnimplementedAccountClientServer()
}

// UnimplementedAccountClientServer must be embedded to have forward compatible implementations.
type UnimplementedAccountClientServer struct {
}

func (UnimplementedAccountClientServer) GetAccount(context.Context, *GetAccountRequest) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedAccountClientServer) mustEmbedUnimplementedAccountClientServer() {}

// UnsafeAccountClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountClientServer will
// result in compilation errors.
type UnsafeAccountClientServer interface {
	mustEmbedUnimplementedAccountClientServer()
}

func RegisterAccountClientServer(s grpc.ServiceRegistrar, srv AccountClientServer) {
	s.RegisterService(&AccountClient_ServiceDesc, srv)
}

func _AccountClient_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountClientServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountClient/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountClientServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountClient_ServiceDesc is the grpc.ServiceDesc for AccountClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AccountClient",
	HandlerType: (*AccountClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _AccountClient_GetAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/account.proto",
}
