// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.2
// source: proto/payment.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaymentIntegrationClient is the client API for PaymentIntegration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentIntegrationClient interface {
	ProcessPayment(ctx context.Context, in *Payment, opts ...grpc.CallOption) (*PaymentResponse, error)
}

type paymentIntegrationClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentIntegrationClient(cc grpc.ClientConnInterface) PaymentIntegrationClient {
	return &paymentIntegrationClient{cc}
}

func (c *paymentIntegrationClient) ProcessPayment(ctx context.Context, in *Payment, opts ...grpc.CallOption) (*PaymentResponse, error) {
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, "/proto.PaymentIntegration/ProcessPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentIntegrationServer is the server API for PaymentIntegration service.
// All implementations must embed UnimplementedPaymentIntegrationServer
// for forward compatibility
type PaymentIntegrationServer interface {
	ProcessPayment(context.Context, *Payment) (*PaymentResponse, error)
	mustEmbedUnimplementedPaymentIntegrationServer()
}

// UnimplementedPaymentIntegrationServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentIntegrationServer struct {
}

func (UnimplementedPaymentIntegrationServer) ProcessPayment(context.Context, *Payment) (*PaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessPayment not implemented")
}
func (UnimplementedPaymentIntegrationServer) mustEmbedUnimplementedPaymentIntegrationServer() {}

// UnsafePaymentIntegrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentIntegrationServer will
// result in compilation errors.
type UnsafePaymentIntegrationServer interface {
	mustEmbedUnimplementedPaymentIntegrationServer()
}

func RegisterPaymentIntegrationServer(s grpc.ServiceRegistrar, srv PaymentIntegrationServer) {
	s.RegisterService(&PaymentIntegration_ServiceDesc, srv)
}

func _PaymentIntegration_ProcessPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentIntegrationServer).ProcessPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PaymentIntegration/ProcessPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentIntegrationServer).ProcessPayment(ctx, req.(*Payment))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentIntegration_ServiceDesc is the grpc.ServiceDesc for PaymentIntegration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentIntegration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PaymentIntegration",
	HandlerType: (*PaymentIntegrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessPayment",
			Handler:    _PaymentIntegration_ProcessPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/payment.proto",
}
